name: Latest Blog Post Workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.caseciter.com/tag/daily-digest/rss/"
          readme_path: "./Jan2026.md"
          max_post_count: 1
          # | allows for a multi-line string template
          # $description pulls the post body provided by the RSS feed
          template: |
            ## [$title]($url)
            $description
            
            ---
